### ISSUE TITLE
Some issues with brew

### ISSUE THREAD

**Issue by rafiki270** [Ether-CLI/Ether#23]
```bash
pro:/Projects/Web/LiveUI/ApiCore (master)$ brew install ether
Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/ether-cli/homebrew-tap/ether.rb:7:in `<class:Ether>'
Please report this to the ether-cli/tap tap!

==> Installing ether from ether-cli/tap
Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/ether-cli/homebrew-tap/ether.rb:7:in `<class:Ether>'
Please report this to the ether-cli/tap tap!

==> Downloading https://github.com/calebkleveter/Ether/releases/download/2018.05.18/macOS-sierra.tar.gz
==> Downloading from https://github.com/Ether-CLI/Ether/releases/download/2018.05.18/macOS-sierra.tar.gz
######################################################################## 100.0%
==> Run `mkdir -p $HOME/Library/Application\ Support/Ether/Templates` to complete installation
Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/ether-cli/homebrew-tap/ether.rb:7:in `<class:Ether>'
Please report this to the ether-cli/tap tap!

🍺  /usr/local/Cellar/ether/2018.05.18: 4 files, 15.1MB, built in 5 seconds
```

**Comment by calebkleveter** [comment]
Fixed https://github.com/Ether-CLI/homebrew-tap/commit/48d83311cc9b0fe6d4c79ccc9fe4301d8d69ab57#diff-1415eff18a0f1d857fd3adcf8e812cd1
